FROM python:3.11-slim

# Instala las dependencias
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

# Comando para iniciar la aplicación
CMD ["python", "test_model_quality.py"]
