FROM python:3.11-slim

# Instalar herramientas de construcción requeridas
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos y instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
