steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/tfm-ms-3/training-repo/export-metrics:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/tfm-ms-3/training-repo/export-metrics:latest']
options:
  logging: CLOUD_LOGGING_ONLY
