# Usa una imagen base de Python
FROM python:3.9-slim

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos de requirements y el script al contenedor
COPY requirements.txt requirements.txt
COPY main.py .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Comando por defecto al ejecutar el contenedor
ENTRYPOINT ["python", "main.py"]
