FROM python:3.10-slim

WORKDIR /app

# Instalar dependencias esenciales del sistema operativo requeridas por XGBoost y LightGBM
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# Copiar e instalar requerimientos usando la caché de Docker de forma eficiente
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script de ejecución
COPY main.py .

# Ejecución nativa para Cloud Run Jobs (Sin servidores web intermedios)
CMD ["python", "main.py"]
