name: Continuous Integration & Deployment (GCP MLOps)

on:
  push:
    branches:
      - main
      - despliegue-modelos

env:
  PROJECT_ID: "tfm-ms-3"
  REGION: "europe-west1"
  WIF_PROVIDER: 'projects/1076362823794/locations/global/workloadIdentityPools/github-wif-pool/providers/github-provider'
  WIF_SERVICE_ACCOUNT: 'sa-github-deployer-v2@tfm-ms-3.iam.gserviceaccount.com'
  VERTEX_SA: 'sa-vertex-train@tfm-ms-3.iam.gserviceaccount.com'
  GCS_BUCKET: 'models-artifacts-tfm'
  
jobs:
  deploy-mlops:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ==========================================
    # FASE AUTENTICACIÓN
    # ==========================================
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WIF_PROVIDER }}
        service_account: ${{ env.WIF_SERVICE_ACCOUNT }}
        token_format: 'access_token'

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # ==========================================
    # FASE A: COMPILAR Y SUBIR IMÁGENES DOCKER
    # ==========================================
    - name: Build and Push Preprocess Image
      run: |
        docker build -t europe-west1-docker.pkg.dev/tfm-ms-3/preprocess-repo/preprocess-pipeline:latest ./preprocess
        docker push europe-west1-docker.pkg.dev/tfm-ms-3/preprocess-repo/preprocess-pipeline:latest

    - name: Build and Push Dash Image
      run: |
        docker build -t europe-west1-docker.pkg.dev/tfm-ms-3/dash-repo/dash-pipeline:latest ./dash
        docker push europe-west1-docker.pkg.dev/tfm-ms-3/dash-repo/dash-pipeline:latest

    - name: Build and Push Monitoring Image
      run: |
        docker build -t europe-west1-docker.pkg.dev/tfm-ms-3/monitoring-repo/monitoring-pipeline:latest ./monitoring
        docker push europe-west1-docker.pkg.dev/tfm-ms-3/monitoring-repo/monitoring-pipeline:latest
    
    - name: Build and Push Training Image
      run: |
        docker build -t europe-west1-docker.pkg.dev/tfm-ms-3/training-repo/training-pipeline:latest ./entrenamiento
        docker push europe-west1-docker.pkg.dev/tfm-ms-3/training-repo/training-pipeline:latest

    # FASE B: ACTUALIZAR Y DESPLEGAR EN CLOUD RUN
    # ==========================================
    - name: Update Preprocess Job
      run: |
        gcloud run jobs update preprocess \
          --image=europe-west1-docker.pkg.dev/tfm-ms-3/preprocess-repo/preprocess-pipeline:latest \
          --region=europe-west1

        
  # ==========================================
    # FASE D: ENTRENAMIENTO AUTOMÁTICO EN VERTEX AI
    # ==========================================
    - name: Submit Model Training Job to Vertex AI
      run: |
        echo "[*] Subiendo el script train_pipeline.py al bucket de staging..."
        gsutil cp ./entrenamiento/train_pipeline.py gs://${{ env.GCS_BUCKET }}/src/train_pipeline.py

        echo "[*] Lanzando el Custom Job de Entrenamiento en Vertex AI..."
        gcloud ai custom-jobs create \
          --region=${{ env.REGION }} \
          --display-name="credit-risk-training-pipeline" \
          --service-account=${{ env.VERTEX_SA }} \
          --worker-pool-spec="machine-type=n1-standard-4,container-image-uri=docker.io/library/python:3.10-slim" \
          --command="sh,-c,pip install --no-cache-dir scikit-learn pandas google-cloud-bigquery google-cloud-storage && python3 -c \"from google.cloud import storage; storage.Client().bucket('${{ env.GCS_BUCKET }}').blob('src/train_pipeline.py').download_to_filename('train_pipeline.py')\" && python3 train_pipeline.py \"\$@\"" \
          --args="--data-source=bigquery,--data-path=tfm-ms-3.analytics_warehouse.df_clean,--gcp-project=${{ env.PROJECT_ID }},--gcs-bucket=${{ env.GCS_BUCKET }},--gcp-location=${{ env.REGION }}"

        echo "[*] Job enviado con éxito. Vertex AI iniciará el entrenamiento usando los datos de BigQuery."